name: check-pushes

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!master'

jobs:
  simple_tests:
    if: contains(github.event.head_commit.message, '%test%')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: npm run lint
      - run: npm run test

  build:
    if: contains(github.event.head_commit.message, '%build%')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: npm run build

  pw_tests:
    if: contains(github.event.head_commit.message, '%pw_test%')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: npm run test:pw-docker:build
      - run: npm run test:pw-docker

  notify:
    if: ${{ needs.simple_tests && needs.build && needs.pw_tests && success() == true && contains(github.event.head_commit.message, '%tg_notify%') }}
    runs-on: ubuntu-latest
    needs:
      - simple_tests
      - build
      - pw_tests

    steps:
      - name: Telegram success notification
        uses: VanyaMate/github-action-telegram-notification@v0.20
        with:
          success: ${{ job.status }}
          tg_bot_token: ${{ secrets.TG_TOKEN_BOT }}
          tg_chat_id: ${{ secrets.TG_CHAT_ID }}
