name: check-pushes

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!master'

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i

  simple_tests:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - run: npm run lint
      - run: npm run test

  build:
    needs:
      - install
      - simple_tests
    runs-on: ubuntu-latest

    steps:
      - run: npm run build

  pw_tests:
    if: contains(github.event.head_commit.message, 'pw_test')
    needs:
      - install
      - simple_tests
      - build
    runs-on: ubuntu-latest

    steps:
      - run: npm run test:pw-docker:build
      - run: npm run test:pw-docker

  notify:
    needs:
      - install
      - simple_tests
      - build
      - pw_tests
    runs-on: ubuntu-latest

    steps:
      - name: Telegram success notification
        uses: VanyaMate/github-action-telegram-notification@v0.20
        with:
          success: ${{ job.status }}
          tg_bot_token: ${{ secrets.TG_TOKEN_BOT }}
          tg_chat_id: ${{ secrets.TG_CHAT_ID }}
